

import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default async function CheckoutLayout({ children }: { children: React.ReactNode}) {

  return (
    <div>
      <NextIntlClientProvider>
      <Toaster position="top-right" reverseOrder={false} />
        <AuthProvider>
          {children}
        </AuthProvider>
      </NextIntlClientProvider>
    </div>
  );
}