
import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Guide",
  description: "Generated by create next app",
};

export default async function ProfileLayout({ children }: { children: React.ReactNode;}) {

  return (
    <div>
      <div className="bg-secondary-color">
        <NextIntlClientProvider>
        <Toaster position="top-right" reverseOrder={false} />
          <AuthProvider>
            {children}
          </AuthProvider>
        </NextIntlClientProvider>
      </div>
    </div>
  );
}