
import type { Metadata } from "next";
import {setRequestLocale} from 'next-intl/server';
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import { Toaster } from 'react-hot-toast';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

export default async function CartLayout({ children, params }: { children: React.ReactNode; params: Promise<{locale: string}>;}) {

  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <div lang={locale}>
      <NextIntlClientProvider>
      <Toaster position="top-right" reverseOrder={false} />
        <AuthProvider>
          {children}
        </AuthProvider>
      </NextIntlClientProvider>
    </div>
  );
}