

import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Login/Register",
  description: "Generated by create next app",
};

export default function AuthLayout({children}: {children: React.ReactNode;}) {
  return (
    <div>
      <Toaster position="top-right" reverseOrder={false} />
      {children}
    </div>
  );
}
